# Generated by Django 5.1 on 2024-10-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.location'),
        ),
    ]
