# Generated by Django 5.1 on 2024-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(related_name='catergories', to='projects.project'),
        ),
    ]
