# Generated by Django 5.1 on 2024-10-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_category_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='projects.category'),
        ),
    ]
