# Generated by Django 5.1 on 2024-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_category_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
